### PR TITLE
Halo regions v2: switching to offset arrays

### LINKED ISSUE #45: Use multiple dispatch to control Poisson solver
[This `if`-statement](https://github.com/ali-ramadhan/Oceananigans.jl/blob/e1be1f0e3f067cdb4236eb5e7b962e0c772ce4d1/src/time_steppers.jl#L140) is not necessary, because the architecture can be known from the array types of the `CellField`s.

Specifically, [this line](https://github.com/ali-ramadhan/Oceananigans.jl/blob/e1be1f0e3f067cdb4236eb5e7b962e0c772ce4d1/src/spectral_solvers.jl#L389) can be changed to

```
function solve_poisson_3d_ppn_planned!(ssp::SpectralSolverParameters, g::RegularCartesianGrid, f::CellField{T}, ϕ::CellField{T}) where T<:CuArray

...

end
```

I think it would actually be preferable to dispatch on the type of the arrays in `RegularCartesianGrid`. However, it does not appear that the arrays representing the coordinates of the grid are parameterized in [the definition of `RegularCartesianGrid`](https://github.com/ali-ramadhan/Oceananigans.jl/blob/e1be1f0e3f067cdb4236eb5e7b962e0c772ce4d1/src/grids.jl#L12). Why is that? 

If the array type of the problem is part of `RegularCartesianGrid`, then dispatch can be used in place of `if`-statements all over the code, especially in `fields.jl`.

Finally, the term 'spectral solvers' is misleading here. The solver does not have spectral accuracy; it simply uses the FFT, which *happens* to be used to solve different problems that have a 'spectral' character.

### LINKED ISSUE #122: We can reduce memory usage in the Poisson solver by a factor of 2.
We don't need to store both `f` and `ϕ`. When converting the `f` Fourier coefficients to `ϕ` coefficients, we can just overwrite the `f` array.

This will be great because the Poisson solver requires `Complex{Float64}` so we free up quite a bit of memory.

We can then get rid of `fCC2` in `StepperTemporaryFields`, move `fCC1` somewhere else like `PoissonSolver` or `Model`, and I think we don't need `fC1` anyways. So we get rid of the `StepperTemporaryFields` struct, and end up storing **zero** intermediate calculations!

### LINKED ISSUE #177: Checkpointer cannot restore when using fields with OffsetArrays.
For now the 10 tests affected by this are skipped with `@test_skip` and will show up as "Broken".

Maybe we just have to define `convert` for Fields with OffsetArrays?

```
    Testing checkpointing...
WARNING: Forcing functions will not be serialized!
[Checkpointer] Serializing model to disk: ./test_model_checkpoint_0.jld
[Checkpointer] Reconstructing FFT plans...
WARNING: Forcing functions will not be serialized!
[Checkpointer] Serializing model to disk: ./test_model_checkpoint_5.jld
[Checkpointer] Reconstructing FFT plans...
Deserializing model from disk: test_model_checkpoint_5.jld
┌ Warning: type Oceananigans.FaceFieldX{OffsetArrays.OffsetArray{Core.Float64,3,Core.Array{Core.Float64,3}},Oceananigans.RegularCartesianGrid{Core.Float64,Base.StepRangeLen{Core.Float64,Base.TwicePrecision{Core.Float64},Base.TwicePrecision{Core.Float64}}}} not present in workspace; reconstructing
└ @ JLD ~/.julia/packages/JLD/1BoSz/src/jld_types.jl:703
┌ Warning: type OffsetArrays.OffsetArray{Core.Float64,3,Core.Array{Core.Float64,3}} not present in workspace; reconstructing
└ @ JLD ~/.julia/packages/JLD/1BoSz/src/jld_types.jl:703
Checkpointing: Error During Test at /home/alir/Oceananigans.jl/test/runtests.jl:293
  Got exception outside of a @test
  MethodError: Cannot `convert` an object of type getfield(JLD, Symbol("##Oceananigans.FaceFieldX{OffsetArrays.OffsetArray{Core.Float64,3,Core.Array{Core.Float64,3}},Oceananigans.RegularCartesianGrid{Core.Float64,Base.StepRangeLen{Core.Float64,Base.TwicePrecision{Core.Float64},Base.TwicePrecision{Core.Float64}}}}#384")) to an object of type FaceFieldX
  Closest candidates are:
    convert(::Type{T}, !Matched::T) where T at essentials.jl:154
  Stacktrace:
   [1] jlconvert(::Type{VelocityFields}, ::JLD.JldFile, ::Ptr{UInt8}) at /home/alir/.julia/packages/JLD/1BoSz/src/jld_types.jl:434
   [2] read_scalar(::JLD.JldDataset, ::HDF5.HDF5Datatype, ::Type) at /home/alir/.julia/packages/JLD/1BoSz/src/JLD.jl:398
   [3] read(::JLD.JldDataset) at /home/alir/.julia/packages/JLD/1BoSz/src/JLD.jl:370
   [4] read_ref(::JLD.JldFile, ::HDF5.HDF5ReferenceObj) at /home/alir/.julia/packages/JLD/1BoSz/src/JLD.jl:502
   [5] jlconvert(::Type{Model{CPU}}, ::JLD.JldFile, ::Ptr{UInt8}) at /home/alir/.julia/packages/JLD/1BoSz/src/jld_types.jl:387
   [6] read_scalar(::JLD.JldDataset, ::HDF5.HDF5Datatype, ::Type) at /home/alir/.julia/packages/JLD/1BoSz/src/JLD.jl:398
   [7] read(::JLD.JldDataset) at /home/alir/.julia/packages/JLD/1BoSz/src/JLD.jl:370
   [8] read(::JLD.JldFile, ::String) at /home/alir/.julia/packages/JLD/1BoSz/src/JLD.jl:346
   [9] restore_from_checkpoint(::String) at /home/alir/Oceananigans.jl/src/output_writers.jl:94
   [10] run_thermal_bubble_checkpointer_tests() at /home/alir/Oceananigans.jl/test/test_output_writers.jl:34
   [11] top-level scope at /home/alir/Oceananigans.jl/test/runtests.jl:295
   [12] top-level scope at /build/julia/src/julia-1.1.0/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
   [13] top-level scope at /home/alir/Oceananigans.jl/test/runtests.jl:294
   [14] top-level scope at /build/julia/src/julia-1.1.0/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
   [15] top-level scope at /home/alir/Oceananigans.jl/test/runtests.jl:290
   [16] top-level scope at /build/julia/src/julia-1.1.0/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
   [17] top-level scope at /home/alir/Oceananigans.jl/test/runtests.jl:14
   [18] include(::String) at ./client.jl:403
   [19] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by ali-ramadhan**
This PR is part 1 of _n_ implementing halo regions (originally PR #167). Here I just replace Arrays and CuArrays with OffsetArrays containing an Array or CuArray. 

An important change is the introduction of the `data(::Field)` function which returns the data stored by the field, i.e. without halo data.

Lots of refactoring had to happen but it was mostly in updating the tests to use the `data` function.

The Poisson solver had to be refactored because FFTW and cuFFT won't work properly on an offset array containing halos. The Poisson solver now keeps track of the right-hand-side, Fourier coefficients, and solution using `solver.storage` which is a regular `Array` or `CuArray`. This cuts down memory usage as well.

Works on #104

Resolves #45
Resolves #122
Resolves #177

### CODE REVIEW

File: src/fields.jl [hunk 1]
```diff
@@ -56,50 +56,50 @@ end
...
 """
- EdgeField(T, arch, g) =  EdgeField(zeros(T, arch, g), g)
+ EdgeField(T, arch, grid) =  EdgeField(zeros(T, arch, grid), grid)
 
- CellField(arch, g) =  CellField(zeros(arch, g), g)
-FaceFieldX(arch, g) = FaceFieldX(zeros(arch, g), g)
-FaceFieldY(arch, g) = FaceFieldY(zeros(arch, g), g)
-FaceFieldZ(arch, g) = FaceFieldZ(zeros(arch, g), g)
- EdgeField(arch, g) =  EdgeField(zeros(arch, g), g)
+ CellField(arch, grid) =  CellField(zeros(arch, grid), grid)
```
Comment (glwagner) [inline src/fields.jl]: 👌

File: src/fields.jl [hunk 2]
```diff
@@ -109,16 +109,12 @@ FaceFieldZ(arch, g) = FaceFieldZ(zeros(arch, g), g)
 @inline lastindex(f::Field, dim) = lastindex(f.data, dim)
 @inline setindex!(f::Field, v, inds...) = setindex!(f.data, v, inds...)
 
+@inline data(f::Field) = f.data[1:f.grid.Nx, 1:f.grid.Ny, 1:f.grid.Nz]
```
Comment (glwagner) [inline src/fields.jl]: may be better to return `view(f.data, 1:Nx, 1:Ny, 1:Nz)`

File: src/grids.jl [hunk 3]
```diff
@@ -14,6 +14,14 @@ struct RegularCartesianGrid{T<:AbstractFloat, R<:AbstractRange} <: Grid{T}
...
     Ny::Int
     Nz::Int
+    # Halo size in (x,y,z).
+    Hx::Int
+    Hy::Int
+    Hz::Int
+    # Total number of grid points (including halo regions).
+    Tx::Int
+    Ty::Int
+    Tz::Int
```
Comment (glwagner) [inline src/grids.jl]: should we `NamedTuple` this stuff? ie `N=(x=16, y=16, z=16)` so that `N.x = 16`? Maybe not now but something to ponder on.

File: src/output_writers.jl [hunk 4]
```diff
@@ -80,7 +80,7 @@ function write_output(model::Model{arch}, chk::Checkpointer) where arch <: Archi
     close(f)
 
     println("[Checkpointer] Reconstructing FFT plans...")
-    model.poisson_solver = init_poisson_solver(arch(), model.grid, model.stepper_tmp.fCC1)
+    model.poisson_solver = PoissonSolver(arch(), model.grid)
```
Comment (glwagner) [inline src/output_writers.jl]: beautiful

File: src/poisson_solvers.jl [hunk 5]
```diff
@@ -1,17 +1,21 @@
...
-    PoissonSolverGPU(g, tmp_rhs)
+PoissonSolver(::CPU, grid::Grid) = PoissonSolverCPU(grid)
+PoissonSolver(::GPU, grid::Grid) = PoissonSolverGPU(grid)
+
+struct PoissonSolverCPU{A1<:AbstractArray, A3<:AbstractArray} <: PoissonSolver
+    kx²::A1
+    ky²::A1
+    kz²::A1
+    storage::A3
+    FFT!
```
Comment (glwagner) [inline src/poisson_solvers.jl]: perhaps make the types of the plans concrete? just need to give them names --- julia will figure out the rest.

File: src/poisson_solvers.jl [hunk 6]
```diff
@@ -20,127 +24,112 @@ let pf2s = Dict(FFTW.ESTIMATE   => "FFTW.ESTIMATE",
...
+    for i in 1:Nx; kx²[i] = (2sin((i-1)*π/Nx)    / (Lx/Nx))^2; end
+    for j in 1:Ny; ky²[j] = (2sin((j-1)*π/Ny)    / (Ly/Ny))^2; end
+    for k in 1:Nz; kz²[k] = (2sin((k-1)*π/(2Nz)) / (Lz/Nz))^2; end
+
+    FFT!  = FFTW.plan_fft!(storage, [1, 2]; flags=planner_flag)
+    IFFT! = FFTW.plan_ifft!(storage, [1, 2]; flags=planner_flag)
+    DCT!  = FFTW.plan_r2r!(storage, FFTW.REDFT10, 3; flags=planner_flag)
+    IDCT! = FFTW.plan_r2r!(storage, FFTW.REDFT01, 3; flags=planner_flag)
+
+    PoissonSolverCPU{typeof(kx²), typeof(storage)}(kx², ky², kz², storage, FFT!, DCT!, IFFT!, IDCT!)
```
Comment (glwagner) [inline src/poisson_solvers.jl]: Omit the manual typing of fields here to make concrete-ifying the fields of `PoissonSolverCPU` pain-free.

File: src/poisson_solvers.jl [hunk 7]
```diff
@@ -20,127 +24,112 @@ let pf2s = Dict(FFTW.ESTIMATE   => "FFTW.ESTIMATE",
...
-struct PoissonSolverGPU{T<:AbstractArray} <: AbstractPoissonSolver
-    kx²
-    ky²
-    kz²
-    dct_factors
-    idct_bfactors
+    nothing
+end
+
+struct PoissonSolverGPU{A1<:AbstractArray, A3<:AbstractArray} <: PoissonSolver
```
Comment (glwagner) [inline src/poisson_solvers.jl]: ditto comments for `PoissonSolverCPU` on concrete-ifying the solver types

File: test/test_dynamics.jl [hunk 8]
```diff
@@ -9,11 +9,12 @@ znodes(ϕ::FaceFieldZ) = repeat(reshape(ϕ.grid.zF[2:end],   1, 1, ϕ.grid.Nz),
 zerofunk(args...) = 0
 
 function set_ic!(model; u=zerofunk, v=zerofunk, w=zerofunk, T=zerofunk, S=zerofunk)
-    model.velocities.u.data .= u.(xnodes(model.velocities.u), ynodes(model.velocities.u), znodes(model.velocities.u))
-    model.velocities.v.data .= v.(xnodes(model.velocities.v), ynodes(model.velocities.v), znodes(model.velocities.v))
-    model.velocities.w.data .= w.(xnodes(model.velocities.w), ynodes(model.velocities.w), znodes(model.velocities.w))
-    model.tracers.T.data    .= T.(xnodes(model.tracers.T),    ynodes(model.tracers.T),    znodes(model.tracers.T))
-    model.tracers.S.data    .= S.(xnodes(model.tracers.S),    ynodes(model.tracers.S),    znodes(model.tracers.S))
+    Nx, Ny, Nz = model.grid.Nx, model.grid.Ny, model.grid.Nz
+    @views model.velocities.u.data[1:Nx, 1:Ny, 1:Nz] .= u.(xnodes(model.velocities.u), ynodes(model.velocities.u), znodes(model.velocities.u))
```
Comment (glwagner) [inline test/test_dynamics.jl]: why not use `data()` here?

File: test/test_time_stepping.jl [hunk 9]
```diff
@@ -39,52 +39,52 @@ end
...
-    w = FaceFieldZ(arch, grid)
-    div_u = CellField(arch, grid)
+    u = FaceFieldX(FT, arch, grid)
+    v = FaceFieldY(FT, arch, grid)
+    w = FaceFieldZ(FT, arch, grid)
+    div_u = CellField(FT, arch, grid)
 
-    u.data .= rand(Nx, Ny, Nz)
-    v.data .= rand(Nx, Ny, Nz)
+    @views data(u) .= rand(FT, Nx, Ny, Nz)
```
Comment (glwagner) [inline test/test_time_stepping.jl]: I'm not 100% sure that this actually sets `u`, but perhaps you verified it? One way to avoid this problem is to have `data` return a view directly (which is also nice because it doesn't allocate [much] memory), as noted earlier in the review

File: test/test_time_stepping.jl [hunk 10]
```diff
@@ -39,52 +39,52 @@ end
...
+    @views data(v) .= rand(FT, Nx, Ny, Nz)
```
Comment (glwagner) [inline test/test_time_stepping.jl]: Note that setting the float type of rand was not previously a feature of this test... ?

File: src/fields.jl (hunk 2 above)
Comment (ali-ramadhan) [reply src/fields.jl]: Yeah in hindsight that would be better. There are a few places where you don't want a view, but often you do want a view.

File: src/grids.jl (hunk 3 above)
Comment (ali-ramadhan) [reply src/grids.jl]: Yeah that might be a good idea. There's also the issue that `Tx, Ty, Tz` is also used for the number of CUDA threads per block, but I figured they're in different structs so it's OK for now.

File: src/poisson_solvers.jl (hunk 5 above)
Comment (ali-ramadhan) [reply src/poisson_solvers.jl]: Good point. Will do.

File: src/grids.jl (hunk 3 above)
Comment (glwagner) [reply src/grids.jl]: I think that is a legitimate concern — harder to read the code and increases potential for bugs. Though less clean, we could use NH and NT for number of halo points and number of total points... or *look to unicode*

File: src/poisson_solvers.jl (hunk 6 above)
Comment (glwagner) [reply src/poisson_solvers.jl]: type inference is your friend!

Comment (ali-ramadhan) [reply src/poisson_solvers.jl]: Lol woops meant to give the :+1:

File: src/fields.jl (hunk 2 above)
Comment (glwagner) [reply src/fields.jl]: RIght — but possibly we should add another function for copying data. Like, copydata.

Comment (glwagner) [reply src/fields.jl]: I believe we should expect a view to behave identically to the array pre-halo regions... ?

File: src/poisson_solvers.jl (hunk 6 above)
Comment (glwagner) [reply src/poisson_solvers.jl]: Oh, the dreaded "emoji typo" --- bane of millennials everywhere!

**Comment by ali-ramadhan** [comment]
All tests pass on the CPU now, so it's almost ready to merge.

Going to make sure all GPU tests pass and I'll clean up the code a bit, especially with more concrete typing and changing `data(::Field` to return a view.

**Comment by glwagner** [comment]
When `data` returns a view, all of the redundant `@views` should be removed.

**Comment by ali-ramadhan** [comment]
> When `data` returns a view, all of the redundant `@views` should be removed.

Yup, that'll be nice!

**Comment by glwagner** [comment]
`data` returning a view is important; it means that you can use `data` when you need to in the inner algorithm.

File: src/grids.jl (hunk 3 above)
Comment (ali-ramadhan) [reply src/grids.jl]: > @johncmarshall54: T and H are very often used for temperatures and depth. Source of confusion? Probably not. But other symbols might be better to represent threads etc etc.

File: src/time_steppers.jl [hunk 11]
```diff
@@ -104,6 +96,22 @@ end
 
 time_step!(model; Nt, Δt) = time_step!(model, Nt, Δt)
 
+function solve_for_pressure!(::CPU, model::Model)
+    Nx, Ny, Nz = model.grid.Nx, model.grid.Ny, model.grid.Nz
+    RHS, ϕ = model.poisson_solver.storage, model.poisson_solver.storage
```
Comment (glwagner) [inline src/time_steppers.jl]: maybe a little late for this comment, but a better name for this variable could be `scratch` --- its not persistent memory storage, but temporary scratch memory space.

File: src/time_steppers.jl [hunk 12]
```diff
@@ -104,6 +96,22 @@ end
...
+
+    solve_poisson_3d_ppn_planned!(model.poisson_solver, model.grid)
+    @views model.pressures.pNHS.data[1:Nx, 1:Ny, 1:Nz] .= real.(ϕ)
```
Comment (glwagner) [inline src/time_steppers.jl]: view view view

Comment (glwagner) [reply src/time_steppers.jl]: note that a view is created each time-step here. We could pre-allocate the view and re-use it on this line. Perhaps an enhancement for the future.

File: src/fields.jl (hunk 2 above)
Comment (ali-ramadhan) [reply src/fields.jl]: Done.

File: src/grids.jl (hunk 3 above)
Comment (ali-ramadhan) [reply src/grids.jl]: We use `Tx, Ty, Tz` for threads but that's going to change soon. Seems like we'll end up with something close to `layout.threads.x`, etc. from PR #249. So there probably won't be a conflict.

`T` and `H` are used for temperature but I guess right now the halo size and total number of grid points are very internal and only used in one or two places so I'll keep them as is because I'm not sure of a better name for them.

File: src/poisson_solvers.jl (hunk 5 above)
Comment (ali-ramadhan) [reply src/poisson_solvers.jl]: Done.

File: test/test_time_stepping.jl (hunk 9 above)
Comment (ali-ramadhan) [reply test/test_time_stepping.jl]: You're right. It wasn't actually setting `u` but test was still passing as the `w` computed from continuity was also zero, and thus the velocity was divergence-free lol.

`data` now returns a view so this has been fixed.

File: test/test_time_stepping.jl (hunk 10 above)
Comment (ali-ramadhan) [reply test/test_time_stepping.jl]: You're right but `FT` is an argument/parameter of the test so I think this is now correct.

**Comment by ali-ramadhan** [comment]
Alright, I think this is ready to be merged.

Performance looks alright. Model has slowed down a tiny bit but that's expected because we're using halo regions but still computing differences the "slow" way with `incmod1` and `decmod1`. The next PR will address this.

**Comment by glwagner** [comment]
Why would the model have slowed down?

**Comment by glwagner** [comment]
6% for a 3D kernel and a 2D loop over a vertical integral isn't bad.

**Comment by ali-ramadhan** [comment]
> Why would the halo regions themselves cause a slowdown?

Probably just extra opportunities for type instabilities, I noticed allocations went up by a tiny bit as well.

I know that  it's supposed to be a zero-cost abstraction but I may have used them in a way that produced some overhead.

**Comment by glwagner** [comment]
True. I guess a performance loss due to type instability isn't super important --- we need to solve type instability anyways.
