### PR TITLE
Get rid of method redefinition warnings during precompile stage

### LINKED ISSUE #366: Supressing harmless warning and error messages
Right now anyone using Oceananigans for the first time sees Casette warnings (https://github.com/vchuravy/GPUifyLoops.jl/issues/94) and CUDA warnings on the CPU.

They're harmless issues but give the feeling of an unstable package.

Would be good to suppress them somehow.

This package might help: https://github.com/JuliaIO/Suppressor.jl

What I see on a CPU:
```
WARNING: Method definition recurse(Cassette.Context{N, M, T, P, B, H} where H<:Union{Cassette.DisableHooks, Nothing} where B<:Union{Nothing, Base.IdDict{Module, Base.Dict{Symbol, Cassette.BindingMeta}}} where P<:Cassette.AbstractPass where T<:Union{Nothing, Cassette.Tag{N, X, E} where E where X where N<:Cassette.AbstractContextName} where M where N<:Cassette.AbstractContextName, Any...) in module Cassette at /home/alir/.julia/packages/Cassette/IwsFs/src/overdub.jl:550 overwritten in module GPUifyLoops at /home/alir/.julia/packages/Cassette/IwsFs/src/overdub.jl:550.
WARNING: Method definition overdub(Cassette.Context{N, M, T, P, B, H} where H<:Union{Cassette.DisableHooks, Nothing} where B<:Union{Nothing, Base.IdDict{Module, Base.Dict{Symbol, Cassette.BindingMeta}}} where P<:Cassette.AbstractPass where T<:Union{Nothing, Cassette.Tag{N, X, E} where E where X where N<:Cassette.AbstractContextName} where M where N<:Cassette.AbstractContextName, Any...) in module Cassette at /home/alir/.julia/packages/Cassette/IwsFs/src/overdub.jl:537 overwritten in module GPUifyLoops at /home/alir/.julia/packages/Cassette/IwsFs/src/overdub.jl:537.
ERROR: LoadError: Could not find CUDA driver library
Stacktrace:
 [1] top-level scope at /home/alir/.julia/packages/CUDAdrv/ADRHQ/src/CUDAdrv.jl:33
 [2] top-level scope at none:2
in expression starting at /home/alir/.julia/packages/CUDAdrv/ADRHQ/src/CUDAdrv.jl:27
┌ Warning: Replacing docs for `Core.nothing :: Union{}` in module `Oceananigans`
└ @ Base.Docs docs/Docs.jl:223
┌ Warning: Replacing docs for `Core.nothing :: Union{}` in module `Oceananigans`
└ @ Base.Docs docs/Docs.jl:223
┌ Warning: Replacing docs for `Core.nothing :: Union{}` in module `Oceananigans`
└ @ Base.Docs docs/Docs.jl:223
┌ Warning: Replacing docs for `Core.nothing :: Union{}` in module `Oceananigans`
└ @ Base.Docs docs/Docs.jl:223
```

### LINKED ISSUE #537: Multiple warnings about "incremental compilation may be fatally broken for this module"
Non-fatal and easy to fix but should probably be done as these look bad to users.

The Casette warnings are non-trivial to fix according to @vchuravy so maybe supressing those warnings might work (see #366).

```
julia> using Oceananigans
[ Info: Precompiling Oceananigans [9e8cae18-63c1-5223-a75c-80ca9d6e9a09]
WARNING: Method definition overdub(Cassette.Context{N, M, T, P, B, H} where H<:Union{Cassette.DisableHooks, Nothing} where B<:Union{Nothing, Base.IdDict{Module, Base.Dict{Symbol, Cassette.BindingMeta}}} where P<:Cassette.AbstractPass where T<:Union{Nothing, Cassette.Tag{N, X, E} where E where X where N<:Cassette.AbstractContextName} where M where N<:Cassette.AbstractContextName, Any...) in module Cassette at /home/alir/.julia/packages/Cassette/YCOeN/src/overdub.jl:524 overwritten in module GPUifyLoops at /home/alir/.julia/packages/Cassette/YCOeN/src/overdub.jl:524.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition recurse(Cassette.Context{N, M, T, P, B, H} where H<:Union{Cassette.DisableHooks, Nothing} where B<:Union{Nothing, Base.IdDict{Module, Base.Dict{Symbol, Cassette.BindingMeta}}} where P<:Cassette.AbstractPass where T<:Union{Nothing, Cassette.Tag{N, X, E} where E where X where N<:Cassette.AbstractContextName} where M where N<:Cassette.AbstractContextName, Any...) in module Cassette at /home/alir/.julia/packages/Cassette/YCOeN/src/overdub.jl:537 overwritten in module GPUifyLoops at /home/alir/.julia/packages/Cassette/YCOeN/src/overdub.jl:537.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition overdub(Cassette.Context{N, M, T, P, B, H} where H<:Union{Cassette.DisableHooks, Nothing} where B<:Union{Nothing, Base.IdDict{Module, Base.Dict{Symbol, Cassette.BindingMeta}}} where P<:Cassette.AbstractPass where T<:Union{Nothing, Cassette.Tag{N, X, E} where E where X where N<:Cassette.AbstractContextName} where M where N<:Cassette.AbstractContextName, Any...) in module Cassette at /home/alir/.julia/packages/Cassette/YCOeN/src/overdub.jl:524 overwritten in module GPUifyLoops at /home/alir/.julia/packages/Cassette/YCOeN/src/overdub.jl:524.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition recurse(Cassette.Context{N, M, T, P, B, H} where H<:Union{Cassette.DisableHooks, Nothing} where B<:Union{Nothing, Base.IdDict{Module, Base.Dict{Symbol, Cassette.BindingMeta}}} where P<:Cassette.AbstractPass where T<:Union{Nothing, Cassette.Tag{N, X, E} where E where X where N<:Cassette.AbstractContextName} where M where N<:Cassette.AbstractContextName, Any...) in module Cassette at /home/alir/.julia/packages/Cassette/YCOeN/src/overdub.jl:537 overwritten in module GPUifyLoops at /home/alir/.julia/packages/Cassette/YCOeN/src/overdub.jl:537.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition TurbulentDiffusivities(Oceananigans.AbstractArchitecture, Oceananigans.AbstractGrid{T} where T, Any, Tuple) in module TurbulenceClosures at /home/alir/Oceananigans.jl/src/TurbulenceClosures/TurbulenceClosures.jl:151 overwritten at /home/alir/Oceananigans.jl/src/TurbulenceClosures/closure_tuples.jl:35.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition with_tracers(Any, Tuple) in module TurbulenceClosures at /home/alir/Oceananigans.jl/src/TurbulenceClosures/TurbulenceClosures.jl:154 overwritten at /home/alir/Oceananigans.jl/src/TurbulenceClosures/closure_tuples.jl:38.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition (::Type{Oceananigans.FPlane{FT} where FT})(Any) in module Oceananigans at /home/alir/Oceananigans.jl/src/coriolis.jl:22 overwritten at /home/alir/Oceananigans.jl/src/coriolis.jl:38.
  ** incremental compilation may be fatally broken for this module **
```

### PR DESCRIPTION
**Pull request by ali-ramadhan**
This PR finally gets rid of all the Casette warnings and a few other similar warnings due to method redefinitions.

Had to refactor the `FPlane` constructor to avoid a method redefinition. I chose to infer the float type `FT` from the inputs and remove the option to explicitly pass in an `FT`. This is a breaking change (hopefully a minor one) but I couldn't think of another approach that would less intrusive.

Suggestions welcome for other ways to resolve the ambiguity between `FPlane` constructors.

Resolves #537
Resolves #366

### CODE REVIEW

File: src/coriolis.jl [hunk 1]
```diff
@@ -33,12 +33,13 @@ If `f` is not specified, it is calculated from `rotation_rate` and
 Also called `FPlane`, after the "f-plane" approximation for the local effect of
 Earth's rotation in a planar coordinate system tangent to the Earth's surface.
 """
-function FPlane(FT=Float64; f=nothing, rotation_rate=nothing, latitude=nothing)
+function FPlane(; f=nothing, rotation_rate=nothing, latitude=nothing)
```
Comment (glwagner) [inline src/coriolis.jl]: Is this the best solution, or should we dispatch on the type of `FT`?

Comment (ali-ramadhan) [reply src/coriolis.jl]: Hmmm, dispatching on the type of `FT` could work but then you'd have to write a new function for each `FT` (might be fine until we start playing around with posits) but would also be breaking because an `FT` must be passed.

Right now `FPlane(f=1e-4)` is still valid but if we dispatched on `FT` then you'd always have to supply an `FT` to dispatch on, e.g. `FPlane(Float64; f=1e-4)` which I feel breaks more code as we usually run with the default `Float64`.

Comment (glwagner) [reply src/coriolis.jl]: The type of `FT` is always `DataType`, is it not?

Comment (glwagner) [reply src/coriolis.jl]: The problem is that this method conflicts with the default constructor `FPlane(f)`, where `f` is expected to be a `Number` of some kind, probably.

Comment (ali-ramadhan) [reply src/coriolis.jl]: Ah of course, that's the most sensible solution. I feel pretty dumb now.

Just committed this change.

Comment (glwagner) [reply src/coriolis.jl]: Well, I got stung by the same problem some time earlier (not sure why the dispatch was removed...), which is why I knew how to fix it.

**Comment by vchuravy** [comment]
Don't depend on master grrml...

**Comment by ali-ramadhan** [comment]
Ah what would be a better way of doing this than `] add Cassette#master`?

**Comment by vchuravy** [comment]
Waiting for me to tag a version of Cassette.

**Comment by ali-ramadhan** [comment]
Yeah that would have been cleaner. Will ask or wait in the future.
